name: "Arch Power Edition - Interactive Session"

on:
  workflow_dispatch:

jobs:
  custom_arch:
    runs-on: ubuntu-latest
    
    # Configuramos tu imagen personalizada
    container:
      image: tomillo037/tomexarch:kde_v.1.5_power_edition_lite
      options: --privileged # Otorga permisos de root reales al contenedor
    
    permissions:
      contents: write

    steps:
      - name: "üìÇ Checkout Repository"
        uses: actions/checkout@v4

      - name: "üõ°Ô∏è Git Ownership Fix"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "Tomillo037"
          git config --global user.email "tu-email@ejemplo.com"

      - name: "‚ö° Iniciar SSHX (Vanta-Violet Mode)"
        run: |
          echo -e "\033[38;5;93m[!] CARGANDO: tomillo037/tomexarch... [OK]\033[0m"
          echo -e "\033[38;5;141m[!] MODO PRIVILEGIADO ACTIVADO\033[0m"
          curl -sSf https://sshx.io/get | sh -s run
